name: Build Horses3D NS Solver (CPU, MPI)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Fortran
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: gfortran
        version: 13

    - name: Setup MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenmpi-dev openmpi-bin

    - name: Install Metis
      run: |
        sudo apt-get install -y cmake
        git clone https://github.com/KarypisLab/METIS.git
        cd METIS
        git checkout tags/v5.1.0
        make config prefix=$HOME/metis
        make
        make install
        echo "METIS_DIR=$HOME/metis" >> $GITHUB_ENV

    - name: Export compiler environment
      run: |
        echo "FC=gfortran" >> $GITHUB_ENV
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
        echo "MPIFC=mpifort" >> $GITHUB_ENV

    - name: Configure Horses3D
      run: |
        ./configure

    - name: Build NS solver
      run: |
        make ns COMPILER=gfortran COMM=PARALLEL WITH_METIS=YES
