name: HORSES3D CPU Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - uses: actions/checkout@v4

      # 2. Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gfortran openmpi-bin libopenmpi-dev \
            cmake make git zlib1g-dev wget tar

      # 3. Setup gfortran (ensures consistent version)
      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1.6.3
        with:
          compiler: gfortran
          version: 13

      # 4. Download and install METIS
      - name: Install METIS
        run: |
          wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz
          tar -xzf metis-5.1.0.tar.gz
          cd metis-5.1.0
          make config prefix=$PWD/build
          make -j$(nproc) install
          echo "METIS_DIR=$PWD/build" >> $GITHUB_ENV

      # 5. Configure HORSES3D
      - name: Configure HORSES3D
        run: |
          cd Solver
          ./configure
